# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build root-config module
      working-directory: root-config
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true

    - name: Build react-utils module
      working-directory: react-utils
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true

    - name: Build react-header module
      working-directory: react-header
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true

    - name: Build react-single module
      working-directory: react-single
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true

    - name: Build react-multiples module
      working-directory: react-multiples
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true

    - name: Build react-lazy module
      working-directory: react-lazy
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true

    - name: Build react-parcel module
      working-directory: react-parcel
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true

    - name: Build react-parcel-form module
      working-directory: react-parcel-form
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true